### ISSUE TITLE
Use type="doi" for citations

### ISSUE THREAD

**Issue by bernt-matthias** [qiime2/galaxy-tools#11]

**Comment by ebolyen** [comment]
Some citations don't have a DOI, [like this one](https://github.com/qiime2/galaxy-tools/blob/main/tools/suite_qiime2_diversity/qiime2_diversity_pcoa-biplot.xml#L499-L509), is it possible to mix citation types?

We could use DOI when it's present with a bibtex fallback. I assume this is allowed since they are different XML nodes.

**Comment by ebolyen** [comment]
Perfect! I'll create an issue over in q2galaxy to render that when possible.

**Comment by ebolyen** [comment]
Superseded by https://github.com/qiime2/q2galaxy/issues/38

**Comment by ebolyen** [comment]
Fixed in latest release!
