### ISSUE TITLE
Tool tests

### ISSUE THREAD

**Issue by bernt-matthias** [qiime2/galaxy-tools#12]
Wondering what your plans are wrt galaxy tool tests. Is there a possibility to auto generate them? Or maybe have manually curated tests that can be accumulated over time in this repo?

**Comment by ebolyen** [comment]
Yes! There is a plan, some details to be worked out in #10.

To elaborate a bit further, we generate tests from written [Usage Examples](https://dev.qiime2.org/latest/api-reference/usage/) which was created in part to let us generate `<test>` sections for Galaxy.

Currently, most plugins are pretty sparse on usage examples, this is expected to improve over time, but there is a small example of it [being rendered to XML here](https://github.com/qiime2/galaxy-tools/blob/main/tools/suite_qiime2_feature-table/qiime2_feature-table_merge.xml#L482-L495) which is [described by the plugin here](https://github.com/qiime2/q2-feature-table/blob/master/q2_feature_table/examples.py#L39-L64). We are able to use the same description to generate documentation as well, and so that's included in the `<help>` additionally.

Our plugins are already all unit-tested, so our approach is to use these as documentation primarily (so we're not in a huge hurry, contributions of course welcome!).

But that isn't the entire story yet either. For integration testing of the QIIME 2 framework and an interface (such as q2galaxy), we also have a plugin which generates currently 621 examples to exercise all of the different parameters available via our type system. This is how we test that q2galaxy's rendered XML is sufficient to roundtrip the arguments. I think a natural next step would be to create a mock toolshed with q2-mystery-stew and demonstrate that that works as well.

**Comment by Oddant1** [comment]
We have tests now
